name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: glm
      run: sudo apt install libglm-dev
    - name: outdir
      run: mkdir bin
    - name: make
      run: make shiny-demo
